### ISSUE TITLE
The body of Api could be a object instead of string ?

### ISSUE THREAD

**Issue by khacluan** [tungv/redux-api-call#26]
@tungv Thanks for your package

Why the data type of the body is a string ?
it may be an object ?

**Comment by tungv** [comment]
Hi Luan,
It's because [global.fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) api doesn't accept object.

![image](https://user-images.githubusercontent.com/1922462/29405437-1f403e88-8368-11e7-946d-2919579270c5.png)

Fortunately, if your entire application only sends body as JSON (which is not always the case, someone wants to send XML or form data or buffer), you can do one of the following options:

1) `JSON.stringify` in body and add `content-type: application/json` in headers
2) write an adapter to do the above tasks if the request contains a `json` property

If you want to write an adapter, please advise this page: https://github.com/tungv/redux-api-call/wiki/Custom-Adapter

At the end of that page, you'll see this example

```js
// stringify a body object and add request headers
const stringify = (next) => async (req) => {
  // only stringify POST, PUT, PATCH requests with body is an object
  if (req.method.match(/POST|PUT|PATCH/) && typeof req.body === 'object') {
    const body = JSON.stringify(req.body);
    const headers = {
      ...req.headers,
      'content-type': 'application/json'
    }
    return next({ ...req, body, headers });
  }

  return next(req);
}
```

This example will convert all POST/PUT/PATCH request with a body prop is an object to JSON request.

PS: make sure your redux-api-call version is 1 or above

**Comment by khacluan** [comment]
I got it @tungv 
Thank you so much
